spring:
  datasource:
    url: jdbc:mysql://localhost:3306/formularios
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create

urlpublica: "https://dominiocliente.com/formularios/"
jwt:
  secret: aaa